KEY_UP       = 0
KEY_DOWN     = 1
KEY_LEFT     = 2
KEY_RIGHT    = 3
KEY_A_BUTTON = 4
KEY_B_BUTTON = 5
KEY_START    = 6
KEY_SELECT   = 7
KEY_ESCAPE   = 8

EVENT_QUIT    = 10
EVENT_KEYDOWN = 11
EVENT_KEYUP   = 12
